# Generated by Django 4.2.6 on 2023-10-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="created_data",
            new_name="created_date",
        ),
        migrations.AlterField(
            model_name="team",
            name="photo",
            field=models.ImageField(upload_to="photos/%y/%m/%D"),
        ),
    ]
